alias depsc='gradle clean install deploy -PliferayHome=liferay-dxp-c -Papp.server.parent.dir=liferay-dxp-c'
alias depsp='gradle clean install deploy -PliferayHome=liferay-dxp-p -Papp.server.parent.dir=liferay-dxp-p'

alias depwc='gradle clean deploy -PliferayHome=liferay-dxp-c -Papp.server.parent.dir=liferay-dxp-c'
alias depwp='gradle clean deploy -PliferayHome=liferay-dxp-p -Papp.server.parent.dir=liferay-dxp-p'

alias deps="gradle clean install deploy"
alias depw="gradle clean deploy"
alias up="git pull"
alias fetch="git fetch --all"
alias remote="git remote -vv"
alias dev="git checkout dev"
alias av="git checkout avanzada"
alias per="git checkout personal"
alias branch="git branch -a"
alias force="git checkout -f"
alias diff="git diff"
alias check="git checkout"
alias status="git status"
alias cancel="git reset HEAD~1"
alias log="git log --oneline"
alias set_remotes="git branch --set-upstream-to=origin/dev dev && git branch --set-upstream-to=avanzada/dev avanzada"
alias up_branches="git remote update origin --prune && git remote update avanzada --prune"

alias portal="cd /C/Users/eRiveRa/comercial && ./bgc.sh update"
alias portalp="cd /C/Users/eRiveRa/personal && ./rivera.sh portal"

alias jet="rm -rf /C/Users/eRiveRa/comercial/angular-5-portlet/build && cd /C/Users/eRiveRa/comercial/angular-5-portlet && gradle build && cp /C/Users/eRiveRa/comercial/angular-5-portlet/build/libs/com.bgeneral.bel.angular.contact.us.web.jar /C/liferay-dxp-c/deploy/"
alias exo="rm -rf /C/Users/eRiveRa/Desktop/angular/eXo-Angular5-Sample-portlet-master/target && cd /C/Users/eRiveRa/Desktop/angular/eXo-Angular5-Sample-portlet-master && mvn install && cp /C/Users/eRiveRa/Desktop/angular/eXo-Angular5-Sample-portlet-master/target/angular-portlet.war /C/liferay-dxp-c/deploy/"

alias belc="cd /C/Users/eRiveRa/comercial"
alias belp="cd /C/Users/eRiveRa/personal"
alias server="cd /C/liferay-dxp-c"

alias chas="cd /C/Users/eRiveRa/comercial/charge-service"
alias chaw="cd /C/Users/eRiveRa/comercial/charge-web"
alias cols="cd /C/Users/eRiveRa/comercial/collector-payment-service"
alias colw="cd /C/Users/eRiveRa/comercial/collector-payment-web"
alias comps="cd /C/Users/eRiveRa/comercial/company-data-info-service"
alias compw="cd /C/Users/eRiveRa/comercial/company-data-info-web"
alias coms="cd /C/Users/eRiveRa/comercial/common-service"
alias comers="cd /C/Users/eRiveRa/comercial/commercial-reports-service"
alias cons="cd /C/Users/eRiveRa/comercial/contact-us-service"
alias conw="cd /C/Users/eRiveRa/comercial/contact-us-web"
alias crew="cd /C/Users/eRiveRa/comercial/credit-card-statement-web"
alias dasw="cd /C/Users/eRiveRa/comercial/dashboard-account-web"
alias intw="cd /C/Users/eRiveRa/comercial/international-reports-web"
alias linw="cd /C/Users/eRiveRa/comercial/line-of-credit-reports-web"
alias loaw="cd /C/Users/eRiveRa/comercial/loan-reports-web"
alias logw="cd /C/Users/eRiveRa/comercial/login-web"
alias mans="cd /C/Users/eRiveRa/comercial/manage-users-service"
alias manw="cd /C/Users/eRiveRa/comercial/manage-users-web"
alias nots="cd /C/Users/eRiveRa/comercial/notification-service"
alias notw="cd /C/Users/eRiveRa/comercial/notifications-config-web"
alias pers="cd /C/Users/eRiveRa/comercial/performed-transactions-service"
alias perw="cd /C/Users/eRiveRa/comercial/performed-transactions-web"
alias pros="cd /C/Users/eRiveRa/comercial/product-service"
alias prow="cd /C/Users/eRiveRa/comercial/product-info-web"
alias rechs="cd /C/Users/eRiveRa/comercial/recharge-service"
alias rechw="cd /C/Users/eRiveRa/comercial/recharge-web"
alias recw="cd /C/Users/eRiveRa/comercial/received-payments-reports-web"
alias reps="cd /C/Users/eRiveRa/comercial/report-service"
alias schw="cd /C/Users/eRiveRa/comercial/scheduled-transactions-web"
alias theme="cd /C/Users/eRiveRa/comercial/bgp-theme"
alias trans="cd /C/Users/eRiveRa/comercial/transaction-service"
alias transfs="cd /C/Users/eRiveRa/comercial/transfer-service"
alias transfw="cd /C/Users/eRiveRa/comercial/transfer-web"
alias ws="cd /C/Users/eRiveRa/comercial/ws-api-services"
alias wsup="git clone http://bgcldevops/banca-en-linea/bgp-bel-portal-comercial/main-portal/ws-api-services.git && gradle clean install deploy"

alias state="rm -rf /C/liferay-dxp-c/osgi/state && rm -rf /C/liferay-dxp-c/work && rm -rf /C/liferay-dxp-p/osgi/state && rm -rf /C/liferay-dxp-p/work"

alias runmongo="mongod --auth"
alias adminmongo="mongo mongodb://edwblinkado:earc1721...edwbd@localhost:27017/admin"

alias sshp="ssh logs@bgcldevopsbv -p 10211"
alias sshc="ssh logs@bgcldevopsbv -p 10311"
alias ssha="ssh logs@bgcldevopsbv -p 10331"
alias ssht="ssh logs@bgcldevopsbv -p 10411"

alias sshpbd="ssh logs@bgcldevopsbv -p 10221"
alias sshcbd="ssh logs@bgcldevopsbv -p 10321"
alias sshtbd="ssh logs@bgcldevopsbv -p 10421"

alias ports="netstat -aon"
